In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:

### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6773, 7094, 9694, 3657],
 [6773, 7094, 9694, 9585],
 [6773, 5196, 9694, 8020],
 [7629, 3506, 6120, 2834, 4145],
 [7629, 3506, 6120, 2834, 7752],
 [7779, 6773, 4859, 9694, 2409],
 [8262, 3946, 5870, 2834]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6773 7094 9694 3657]
 [   0    0    0    0 6773 7094 9694 9585]
 [   0    0    0    0 6773 5196 9694 8020]
 [   0    0    0 7629 3506 6120 2834 4145]
 [   0    0    0 7629 3506 6120 2834 7752]
 [   0    0    0 7779 6773 4859 9694 2409]
 [   0    0    0    0 8262 3946 5870 2834]]


In [9]:
## feature representation
dim=10

In [10]:

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\TrAb799\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:

model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step


array([[[-0.00197604,  0.03541512,  0.04397343,  0.02220337,
          0.00703499,  0.02381455, -0.01949467,  0.00086275,
         -0.00131395, -0.00647187],
        [-0.00197604,  0.03541512,  0.04397343,  0.02220337,
          0.00703499,  0.02381455, -0.01949467,  0.00086275,
         -0.00131395, -0.00647187],
        [-0.00197604,  0.03541512,  0.04397343,  0.02220337,
          0.00703499,  0.02381455, -0.01949467,  0.00086275,
         -0.00131395, -0.00647187],
        [-0.00197604,  0.03541512,  0.04397343,  0.02220337,
          0.00703499,  0.02381455, -0.01949467,  0.00086275,
         -0.00131395, -0.00647187],
        [ 0.03721463, -0.00229456, -0.02111104,  0.02325115,
         -0.01424599,  0.00365734,  0.03624309, -0.02382907,
         -0.01541395,  0.02257002],
        [-0.01612456, -0.02176784,  0.01951062,  0.00542162,
          0.02972344, -0.02852553,  0.02830597, -0.0282477 ,
          0.04080286, -0.01400914],
        [-0.03014427,  0.03231194, -0.04569805, -0.0